In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

### **Count of number of agreement and conflicts by ceasefire provisions**

In [10]:
df_panel = pd.read_csv('../../data/output/conflict_level/conflict_panel.csv')
df_panel.loc[df_panel['cea_agreement']==1].groupby('ce')['conflict_id'].nunique().reset_index()

/var/folders/fz/1mp_qssx1z546qc9z63nq3rm0000gn/T/ipykernel_18500/2439078267.py:1: DtypeWarning: Columns (84,85,87,88,91,92,93,96,97,98,99,100,101,102,108) have mixed types. Specify dtype option on import or set low_memory=False.
  df_panel = pd.read_csv('../../data/output/conflict_level/conflict_panel.csv')

    ce  conflict_id
0  0.0            2
1  1.0           11
2  2.0           30
3  3.0           38

In [38]:
for treatment in [ 'agreement', 'comp_agreement', 'subs_agreement', 'cea_agreement',]:
    print('Treatment', treatment)
    print(df_panel[df_panel[treatment] == 1].groupby('ce').size().reset_index(name='n_agreements'))

Treatment agreement
    ce  n_agreements
0  0.0           290
1  1.0           119
2  2.0           201
3  3.0           135
Treatment comp_agreement
    ce  n_agreements
0  0.0            21
1  1.0             3
2  2.0            12
3  3.0            20
Treatment subs_agreement
    ce  n_agreements
0  0.0            99
1  1.0            27
2  2.0            36
3  3.0            28
Treatment cea_agreement
    ce  n_agreements
0  0.0             3
1  1.0            32
2  2.0            88
3  3.0           103

In [27]:
df_pax = pd.read_csv('../../data/input/pax/pax_data_2144_agreements_v9_10.csv', low_memory=False)
df_pax.columns = df_pax.columns.str.lower()

# conflicts that exist in your panel
ucdp_conflicts = df_panel['conflict_id'].dropna().unique()

# keep only PAX agreements tied to those conflicts
df_pax_ucdp = df_pax[df_pax['ucdpcon'].isin(ucdp_conflicts)].copy()

# example for comprehensive agreements
df_pax_ucdp['comp_agreement'] = (df_pax_ucdp['stage'].str.lower() == 'subcomp').astype(int)

df_pax_ucdp.loc[df_pax_ucdp['comp_agreement'] == 1] \
    .groupby('ce')['agtid'] \
    .nunique() \
    .reset_index(name='n_agreements')

   ce  n_agreements
0   0            49
1   1             6
2   2            18
3   3            23